model_list:
  - model_name: bedrock-nova
    litellm_params:
      model: bedrock/amazon.nova-2-lite-v1:0
      aws_region_name: us-east-1
  - model_name: bedrock-jamba
    litellm_params:
      model: bedrock/ai21.jamba-1-5-mini-v1:0
      aws_region_name: us-east-1
  - model_name: groq-llama
    litellm_params:
      model: groq/llama-3.1-8b-instant

guardrails:
  - guardrail_name: hiddenlayer-pii-pre
    litellm_params:
      guardrail: custom_guardrail.HiddenLayerPIIGuardrail
      mode: pre_call
      default_on: true

  - guardrail_name: hiddenlayer-pii-post
    litellm_params:
      guardrail: custom_guardrail.HiddenLayerPIIGuardrail
      mode: post_call
      default_on: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY